baseURL = "https://example.org/"
languageCode = "en-us"
title = "Toma"

copyright = "Toma Yuen"

[markup.goldmark.renderer]
unsafe = true 

[params]
footer = "Custom footer text, ***can include markdown.***"
slogan = "slogaaaaaan"

[[menu.main]]
identifier = "activities"
name = "Activities"
weight = 20

[menu.main.params]
divider = true