baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Toma'

copyright = "Future Web Design"

[markup.goldmark.renderer]
unsafe = true 

[params]
footer = "Custom footer text, ***can include markdown.***"
slogan = "slogaaaaaan"